enum JobTicketType{
    // GeneratorToWorld
    CHUNKFROMGENERATOR,

    // ProtocolToWorld
    ANIMATIONJOB,
    CHATTOWORLD,
    CLICKWINDOWJOB,
    CLIENTSLOTCHANGE,
    CLOSEWINDOWJOB,
    ENTITYACTIONJOB,
    PLAYERBLOCKPLACE,
    PLAYERDIGGINGJOB,
    SENDPLAYERPOSTOWORLD,

    // WorldToGenerator
    GENERATECHUNKREQUEST,
    GENCHUNKREQ2,

    // WorldToProtocol
    BLOCKUPDATETOPLAYER,
    CANSPAWN,
    CHATTOPROTOCOL,
    CONFIRMTRANSACTION,
    DESTROYENTITYJOB,
    ENTITYMOVE,
    OPENCLOSEWINDOW,
    SENDITEM,
    SENDPLAYER,
    SENDPLAYERLOGIN,
    SENDPLAYERPOS,
    SENDTHREADAREA,
    SENDWINDOWITEM,

    // WorldToWorld
    CHUNKCLAINTOTHREADAREA,
    CHUNKSFROMTAREA,
    CHUNKTOTHREADAREA,
    EXPANDSYNCHEDAREA,
    EXTERNALPLAYER,
    SENDCOMPRESSEDCHUNKS,
    UNCLAIMREGION,
    UNCLAIMREGIONLOCAL,

    // root
    GIVEPLAYERUUID,
    JOINTHREADAREA,
    JOINWORLD,
    LOADCHUNK,
    REDIRECT,
    REDIRECT2,
    SENDCHUNKS,
    SENDPACKET
};
